name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sample-job-on-the-runner-machine:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: DUMMY_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: DUMMY_AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - uses: actions/checkout@v3
      - run: aws dynamodb create-table --cli-input-json file://users-table.json --endpoint-url http://localhost:8000
      - run: aws dynamodb describe-table --table-name users-table --endpoint-url http://localhost:8000
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
  sample-job-in-containers:
    runs-on: ubuntu-latest
    container: node:16
    env:
      AWS_ACCESS_KEY_ID: DUMMY_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: DUMMY_AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
      - run: aws dynamodb create-table --cli-input-json file://users-table.json --endpoint-url http://dynamodb:8000
      - run: aws dynamodb describe-table --table-name users-table --endpoint-url http://dynamodb:8000
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
